name: DynamicMinigames
version: '1.0-SNAPSHOT'
main: me.cable.dm.DynamicMinigames
api-version: '1.21'

depend:
  - ActionsAPI
  - DecentHolograms

commands:
  dynamicminigames:
    permission: "dynamicminigames.command.dynamicminigames"
    aliases:
      - "dm"
  minigame:
    permission: "dynamicminigames.command.minigame"
    aliases:
      - "mg"